version: "2"

services:

  backend:
    container_name: backend
    image: dev/backend
    build:
      context: ./services/backend
      dockerfile: ./docker/Dockerfile
    ports:
      - "8081:8000"
    volumes:
      - "./services/backend/src:/workspace/src"
      - "./services/backend/requirements.txt:/workspace/requirements.txt"
    env_file:
      - "./environment/local.env"

  migrations:
    container_name: migrations
    image: dev/migrations
    build:
      context: ./services/migrations
      dockerfile: ./docker/Dockerfile
    env_file:
      - "./environment/local.env"
    volumes:
      - "./services/migrations:/usr/migrations"
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    logging:
      driver: none  # change to json-file if you want logs.
