version: 2

services:

  migrations:
    container_name: migrations
    image: famly/migrations:local
    build:
      context: ./db-migrations
      dockerfile: ./docker/Dockerfile
    environment:
      MODE: "development"
      MYSQL_DBNAME: "example"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_HOST: "mysql"
    volumes:
      - "./services/migrations:/usr/migrations"
    depends_on:
      - mysql


  mysql:
    container_name: mysql
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    logging:
      driver: none  # change to json-file if you want logs.
